### ISSUE TITLE
 Report an issue button not working

### ISSUE THREAD

**Issue by ColinDaglish** [datasciencecampus/coding-in-the-open#6]
**Describe the bug**
The 'report an issue' button on the webpage is not working. It returns a 404 error. 

**To Reproduce**
Steps to reproduce the behaviour:

Go to main page
In the upper right quadrant of the screen, select 'report an issue' 
Opens a new page with 404 error. 

**Screenshots**
![location on page](https://github.com/datasciencecampus/coding-in-the-open/assets/87810570/e1c02d74-9295-4144-bb3e-4a7861f02c76)
![404 error](https://github.com/datasciencecampus/coding-in-the-open/assets/87810570/2da22bd7-6d56-4f4d-9269-3437f63a5f7a)

**Environment (please complete the following information):**
Google Chrome

**Additional context**

**Comment by r-leyshon** [comment]
Ah, is that in a locally rendered html file @ColinDaglish  ? If I follow the link on the served site I get through to a new issue on the repo.

**Comment by r-leyshon** [comment]
Just checking with you @ColinDaglish , can you confirm the button works for you on the served website?

**Comment by ColinDaglish** [comment]
Yep seems to work now 👍
